---
abstract: 'XS Levenshtein edit distance.'
author:
  - 'Nick Logan <ugexe@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0.9801'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Levenshtein-XS
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.008'
resources:
  bugtracker: https://github.com/ugexe/Text--Levenshtein--XS/issues
  repository: https://github.com/ugexe/Text--Levenshtein--XS
version: '0.31'
